package com.trademind.events.audit.enums;

public enum AuditAction {

    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,

    INVENTORY_UPDATED,

    ORDER_CREATED,
    ORDER_CANCELLED,
    ORDER_STATUS_CHANGED,

    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,

    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTERED,
    USER_DELETED,
    USER_RESTORED,
    TOKEN_REFRESHED,
    USER_UPDATED,

    BULK_PRODUCT_ADDED,

    UNKNOWN
}