server:
  port: 8089

spring:
  application:
    name: audit-service

  datasource:
    url: jdbc:postgresql://localhost:5432/audit_db
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: audit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"


kafka:
  topics:
    audit-log: audit-log-topic