server:
  port: 8091

spring:
  application:
    name: cart-service


  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true




