server:
  port: 8090

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: postgres
    password: 1234

  cache:
    type: redis

    data:
      redis:
        host: localhost
        port: 6379
        timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

resilience4j:
  circuitbreaker:
    instances:
      analyticsService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  timelimiter:
    instances:
      analyticsService:
        timeoutDuration: 2s